### ISSUE TITLE
Can't find template if the subjid is given on the commandline vs interpretted from dataset

### ISSUE THREAD

**Issue by jstout211** [nih-megcore/nih_to_mne#12]
Copying data files to sub-DEC105_ses-00_task-ASSR_run-01_meg.ds
Writing '/data/Indiv_fMRI_TMS/ASD/DECIBELS_DATA/BIDS/sub-DEC105/ses-00/sub-DEC105_ses-00_scans.tsv'...
Wrote /data/Indiv_fMRI_TMS/ASD/DECIBELS_DATA/BIDS/sub-DEC105/ses-00/sub-DEC105_ses-00_scans.tsv entry with meg/sub-DEC105_ses-00_task-ASSR_run-01_meg.ds.
Traceback (most recent call last):
  File "/vf/users/MEGmodules/modules/mne1.0/bin/make_meg_bids.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/vf/users/MEGmodules/modules/mne1.0_extras/nih_to_mne/nih2mne/make_meg_bids.py", line 430, in <module>
    template_meg = glob.glob(op.join(args.meg_input_dir, subjid+'*.ds'))[0]

**Comment by jstout211** [comment]
Temporary Hack - 

-    template_meg = glob.glob(op.join(args.meg_input_dir, subjid+'*.ds'))[0]
+    template_meg = glob.glob(op.join(args.meg_input_dir, '*.ds'))[0]

Will need a better solution so that this references multi subject folders
